import {Notification} from '../node_modules/prendus-services/typings/notification';
import {Video} from '../node_modules/prendus-services/typings/video';
import {Quiz} from '../node_modules/prendus-services/typings/quiz';
import {Concept} from '../node_modules/prendus-services/typings/concept';
import {QuestionSettings} from '../node_modules/prendus-services/typings/question-settings';
import {QuestionMetaData} from '../node_modules/prendus-services/typings/question-meta-data';
import {User} from '../node_modules/prendus-services/typings/user';
import {UserType} from '../node_modules/prendus-services/typings/user-type';
import {UserMetaData} from '../node_modules/prendus-services/typings/user-meta-data';
import {Course} from '../node_modules/prendus-services/typings/course';
import {CourseLessonData} from '../node_modules/prendus-services/typings/course-lesson-data';
import {Lesson} from '../node_modules/prendus-services/typings/lesson';
import {Discipline} from '../node_modules/prendus-services/typings/discipline';
import {Subject} from '../node_modules/prendus-services/typings/subject';
import {QuestionScaffold} from '../node_modules/prendus-services/typings/question-scaffold';
import {QuestionScaffoldAnswer} from '../node_modules/prendus-services/typings/question-scaffold-answer';
import {Assignment} from '../node_modules/prendus-services/typings/assignment';

export interface Action {
    readonly questionId?: string;
	readonly type: string;
	readonly notificationType?: Notification;
	readonly notificationText?: string;
  readonly courses?: Course[];
  readonly starredCourses?: Course[];
  readonly sharedCourses?: Course[];
  readonly lessons?: CourseLessonData[];
  readonly videos?: Video[];
  readonly quizzes?: Quiz[];
  readonly currentLesson?: {};
  readonly currentCourse?: Course;
  readonly currentLessonVideoId?: string;
  readonly currentLessonVideoTitle?: string;
  readonly currentLessonVideoUrl?: string
	readonly concept?: Concept;
	readonly currentVideo?: Video;
  readonly user?: User;
	readonly unverifiedTeachers?: User[];
	readonly verifiedTeachers?: User[];
  readonly courseLessons?: CourseLessonData[];
  readonly currentEditQuizId?: string;
  readonly currentEditLessonId?: string;
  readonly jwt?: string;
  readonly emails?: string[];
  readonly uid?: string;
  readonly courseId?: string;
  readonly lessonId?: string;
  readonly quizId?: string;
  readonly videoId?: string;
	readonly userQuestionIds?: [string];
	readonly publicQuestionIds?: [string];
	readonly quizQuestionIds?: [string];
	readonly quizQuestionsData?: QuestionMetaData[];
	readonly quizQuestionSettings?: QuestionSettings;
	readonly visibility?: string;
	readonly userType?: UserType;
  readonly userMetaData?: UserMetaData;
	readonly lesson?: Lesson;
	readonly lessonKey?: string;
	readonly orderedLessons?: CourseLessonData[];
	readonly id?: string;
	readonly title?: string;
	readonly url?: string;
	readonly lessonsArray?: Lesson[];
	readonly coursesArray?: Course[];
	readonly disciplines?: Discipline[];
	readonly chosenDiscipline?: Discipline;
	readonly subjects?: Subject[];
	readonly chosenSubject?: Subject;
	readonly chosenConcept?: Concept;
	readonly chosenLesson?: Lesson;
	readonly disableNext?: boolean;
	readonly currentQuestionScaffold?: QuestionScaffold;
	readonly currentQuestionScaffoldExample?: QuestionScaffold;
	readonly questionScaffoldAnswers?: QuestionScaffoldAnswer[];
	readonly exampleQuestionScaffoldAnswers?: QuestionScaffoldAnswer[];
	readonly comments?: string[];
	readonly selectedIndex?: number;
	readonly myIndex?: number;
	readonly answers?: string[];
	readonly explanation?: string;
	readonly questionStem?: string;
	readonly answerText?: string;
	readonly numberOfAnswers?: number;
	readonly ltiState?: string;
	readonly enrolledCourses?: Course[];
    readonly assignments?: {
        [uuid: string]: Assignment;
    };
    readonly assignment?: Assignment;
	readonly questionScaffoldQuiz?: Quiz;
	readonly ltiJwt?: string;
};
